list: $/amjadkhan/jobs/models/application/columns.yaml
modelClass: AmjadKhan\Jobs\Models\Application
title: applications
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'AmjadKhan/jobs/applications/update/:id'
