list: $/amjadkhan/jobs/models/department/columns.yaml
modelClass: AmjadKhan\Jobs\Models\Department
title: Departments
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'AmjadKhan/jobs/departments/update/:id'
